### ISSUE TITLE
[877371] plinth: Selecting Configuration->Certificates (Let's Encrypt) fail

### ISSUE THREAD

**Issue by jvalleroy** [freedombox/Plinth#1040]

**Comment by jvalleroy** [comment]
BTS_msg_id: <2flmv5bsarz.fsf@diskless.uio.no>
BTS author: Petter Reinholdtsen <pere@hungry.com>

Package: plinth
Version: 0.15.2+ds-1
Severity: important

When using the web GUI and selecting Configuration->Certificates (Let's
Encrypt), I get a 500 internal server error.  This is the output in
/var/log/plinth/status.log when it happen:

[2017-10-01 05:18:15,289] plinth.actions INFO     Executing command - ['sudo', '-n', '/usr/share/plinth/actions/letsencrypt', 'get-status']
[2017-10-01 05:18:17,130] plinth.actions INFO     Executing command - ['sudo', '-n', '/usr/share/plinth/actions/letsencrypt', 'manage_hooks', 'status']
[2017-10-01 05:18:17,650] django.request ERROR    Internal Server Error: /plinth/sys/letsencrypt/
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/usr/lib/python3/dist-packages/django/core/handlers/base.py", line 249, in _legacy_get_response
    response = self._get_response(request)
  File "/usr/lib/python3/dist-packages/django/core/handlers/base.py", line 217, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/lib/python3/dist-packages/django/core/handlers/base.py", line 215, in _get_response
    response = response.render()
  File "/usr/lib/python3/dist-packages/django/template/response.py", line 107, in render
    self.content = self.rendered_content
  File "/usr/lib/python3/dist-packages/django/template/response.py", line 84, in rendered_content
    content = template.render(context, self._request)
  File "/usr/lib/python3/dist-packages/django/template/backends/django.py", line 66, in render
    return self.template.render(context)
  File "/usr/lib/python3/dist-packages/django/template/base.py", line 207, in render
    return self._render(context)
  File "/usr/lib/python3/dist-packages/django/template/base.py", line 199, in _render
    return self.nodelist.render(context)
  File "/usr/lib/python3/dist-packages/django/template/base.py", line 990, in render
    bit = node.render_annotated(context)
  File "/usr/lib/python3/dist-packages/django/template/base.py", line 957, in render_annotated
    return self.render(context)
  File "/usr/lib/python3/dist-packages/django/template/loader_tags.py", line 177, in render
    return compiled_parent._render(context)
  File "/usr/lib/python3/dist-packages/django/template/base.py", line 199, in _render
    return self.nodelist.render(context)
  File "/usr/lib/python3/dist-packages/django/template/base.py", line 990, in render
    bit = node.render_annotated(context)
  File "/usr/lib/python3/dist-packages/django/template/base.py", line 957, in render_annotated
    return self.render(context)
  File "/usr/lib/python3/dist-packages/django/template/loader_tags.py", line 177, in render
    return compiled_parent._render(context)
  File "/usr/lib/python3/dist-packages/django/template/base.py", line 199, in _render
    return self.nodelist.render(context)
  File "/usr/lib/python3/dist-packages/django/template/base.py", line 990, in render
    bit = node.render_annotated(context)
  File "/usr/lib/python3/dist-packages/django/template/base.py", line 957, in render_annotated
    return self.render(context)
  File "/usr/lib/python3/dist-packages/django/template/loader_tags.py", line 72, in render
    result = block.nodelist.render(context)
  File "/usr/lib/python3/dist-packages/django/template/base.py", line 990, in render
    bit = node.render_annotated(context)
  File "/usr/lib/python3/dist-packages/django/template/base.py", line 957, in render_annotated
    return self.render(context)
  File "/usr/lib/python3/dist-packages/django/template/loader_tags.py", line 72, in render
    result = block.nodelist.render(context)
  File "/usr/lib/python3/dist-packages/django/template/base.py", line 990, in render
    bit = node.render_annotated(context)
  File "/usr/lib/python3/dist-packages/django/template/base.py", line 957, in render_annotated
    return self.render(context)
  File "/usr/lib/python3/dist-packages/django/template/loader_tags.py", line 72, in render
    result = block.nodelist.render(context)
  File "/usr/lib/python3/dist-packages/django/template/base.py", line 990, in render
    bit = node.render_annotated(context)
  File "/usr/lib/python3/dist-packages/django/template/base.py", line 957, in render_annotated
    return self.render(context)
  File "/usr/lib/python3/dist-packages/django/template/defaulttags.py", line 322, in render
    return nodelist.render(context)
  File "/usr/lib/python3/dist-packages/django/template/base.py", line 990, in render
    bit = node.render_annotated(context)
  File "/usr/lib/python3/dist-packages/django/template/base.py", line 957, in render_annotated
    return self.render(context)
  File "/usr/lib/python3/dist-packages/django/template/defaulttags.py", line 458, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "/usr/lib/python3/dist-packages/django/urls/base.py", line 91, in reverse
    return force_text(iri_to_uri(resolver._reverse_with_prefix(view, prefix, *args, **kwargs)))
  File "/usr/lib/python3/dist-packages/django/urls/resolvers.py", line 497, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'toggle_hooks' with arguments '('',)' not found. 1 pattern(s) tried: ['sys/letsencrypt/toggle_hooks/(?P<domain>[^/]+)/$']

-- 
Happy hacking
Petter Reinholdtsen

**Comment by JoKeyser** [comment]
Hm, not sure whether I can help here, I guess something went wrong in packaging? I can't reproduce this if I checkout v0.15.x (should I?)...

**Comment by jvalleroy** [comment]
I'm not sure what lead to this situation. However, it looks like there are some cases where status.current_domain.name is used, without being checked first:
https://github.com/freedombox/Plinth/blob/master/plinth/modules/letsencrypt/templates/letsencrypt.html#L153

**Comment by jvalleroy** [comment]
@JoKeyser If the domain name on the Configure page is cleared, what should happen on the Certificates page? Should the "Certificate renewal management and use by other modules" section be shown at all?

**Comment by JoKeyser** [comment]
@jvalleroy sorry does look like a bug of my implementation after all. I believe it would be good if the section is shown, but in an "inactive" state, with information what steps to take to use it. That way the option is discoverable without the manual.

**Comment by jvalleroy** [comment]
Fixed in #1073.

**Comment by FedericoCeratto** [comment]
BTS_msg_id: <2flmv5bsarz.fsf@diskless.uio.no>
BTS author: Petter Reinholdtsen <pere@hungry.com>

Package: plinth
Version: 0.15.2+ds-1
Severity: important

When using the web GUI and selecting Configuration->Certificates (Let's
Encrypt), I get a 500 internal server error.  This is the output in
/var/log/plinth/status.log when it happen:

[2017-10-01 05:18:15,289] plinth.actions INFO     Executing command - ['sudo', '-n', '/usr/share/plinth/actions/letsencrypt', 'get-status']
[2017-10-01 05:18:17,130] plinth.actions INFO     Executing command - ['sudo', '-n', '/usr/share/plinth/actions/letsencrypt', 'manage_hooks', 'status']
[2017-10-01 05:18:17,650] django.request ERROR    Internal Server Error: /plinth/sys/letsencrypt/
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/usr/lib/python3/dist-packages/django/core/handlers/base.py", line 249, in _legacy_get_response
    response = self._get_response(request)
  File "/usr/lib/python3/dist-packages/django/core/handlers/base.py", line 217, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/lib/python3/dist-packages/django/core/handlers/base.py", line 215, in _get_response
    response = response.render()
  File "/usr/lib/python3/dist-packages/django/template/response.py", line 107, in render
    self.content = self.rendered_content
  File "/usr/lib/python3/dist-packages/django/template/response.py", line 84, in rendered_content
    content = template.render(context, self._request)
  File "/usr/lib/python3/dist-packages/django/template/backends/django.py", line 66, in render
    return self.template.render(context)
  File "/usr/lib/python3/dist-packages/django/template/base.py", line 207, in render
    return self._render(context)
  File "/usr/lib/python3/dist-packages/django/template/base.py", line 199, in _render
    return self.nodelist.render(context)
  File "/usr/lib/python3/dist-packages/django/template/base.py", line 990, in render
    bit = node.render_annotated(context)
  File "/usr/lib/python3/dist-packages/django/template/base.py", line 957, in render_annotated
    return self.render(context)
  File "/usr/lib/python3/dist-packages/django/template/loader_tags.py", line 177, in render
    return compiled_parent._render(context)
  File "/usr/lib/python3/dist-packages/django/template/base.py", line 199, in _render
    return self.nodelist.render(context)
  File "/usr/lib/python3/dist-packages/django/template/base.py", line 990, in render
    bit = node.render_annotated(context)
  File "/usr/lib/python3/dist-packages/django/template/base.py", line 957, in render_annotated
    return self.render(context)
  File "/usr/lib/python3/dist-packages/django/template/loader_tags.py", line 177, in render
    return compiled_parent._render(context)
  File "/usr/lib/python3/dist-packages/django/template/base.py", line 199, in _render
    return self.nodelist.render(context)
  File "/usr/lib/python3/dist-packages/django/template/base.py", line 990, in render
    bit = node.render_annotated(context)
  File "/usr/lib/python3/dist-packages/django/template/base.py", line 957, in render_annotated
    return self.render(context)
  File "/usr/lib/python3/dist-packages/django/template/loader_tags.py", line 72, in render
    result = block.nodelist.render(context)
  File "/usr/lib/python3/dist-packages/django/template/base.py", line 990, in render
    bit = node.render_annotated(context)
  File "/usr/lib/python3/dist-packages/django/template/base.py", line 957, in render_annotated
    return self.render(context)
  File "/usr/lib/python3/dist-packages/django/template/loader_tags.py", line 72, in render
    result = block.nodelist.render(context)
  File "/usr/lib/python3/dist-packages/django/template/base.py", line 990, in render
    bit = node.render_annotated(context)
  File "/usr/lib/python3/dist-packages/django/template/base.py", line 957, in render_annotated
    return self.render(context)
  File "/usr/lib/python3/dist-packages/django/template/loader_tags.py", line 72, in render
    result = block.nodelist.render(context)
  File "/usr/lib/python3/dist-packages/django/template/base.py", line 990, in render
    bit = node.render_annotated(context)
  File "/usr/lib/python3/dist-packages/django/template/base.py", line 957, in render_annotated
    return self.render(context)
  File "/usr/lib/python3/dist-packages/django/template/defaulttags.py", line 322, in render
    return nodelist.render(context)
  File "/usr/lib/python3/dist-packages/django/template/base.py", line 990, in render
    bit = node.render_annotated(context)
  File "/usr/lib/python3/dist-packages/django/template/base.py", line 957, in render_annotated
    return self.render(context)
  File "/usr/lib/python3/dist-packages/django/template/defaulttags.py", line 458, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "/usr/lib/python3/dist-packages/django/urls/base.py", line 91, in reverse
    return force_text(iri_to_uri(resolver._reverse_with_prefix(view, prefix, *args, **kwargs)))
  File "/usr/lib/python3/dist-packages/django/urls/resolvers.py", line 497, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'toggle_hooks' with arguments '('',)' not found. 1 pattern(s) tried: ['sys/letsencrypt/toggle_hooks/(?P<domain>[^/]+)/$']

-- 
Happy hacking
Petter Reinholdtsen

**Comment by FedericoCeratto** [comment]
BTS_msg_id: <2d679bd4-2e09-f879-68ed-daf32010f1fd@mailbox.org>
BTS author: James Valleroy <jvalleroy@mailbox.org>

This is an OpenPGP/MIME signed message (RFC 4880 and 3156)
--9lM2xcNGB4K1rn9Xng8IFJDFwCIJpHL05
Content-Type: multipart/mixed; boundary="6GrHH4Klan9ojdG73K5v9fOCV9A4sOR8f";
 protected-headers="v1"
From: James Valleroy <jvalleroy@mailbox.org>
To: 877371@bugs.debian.org
Message-ID: <2d679bd4-2e09-f879-68ed-daf32010f1fd@mailbox.org>
Subject: Re: plinth: Selecting Configuration->Certificates (Let's Encrypt)
 fail
References: <2flmv5bsarz.fsf@diskless.uio.no>
 <2flmv5bsarz.fsf@diskless.uio.no>
In-Reply-To: <2flmv5bsarz.fsf@diskless.uio.no>

--6GrHH4Klan9ojdG73K5v9fOCV9A4sOR8f
Content-Type: text/plain; charset=utf-8
Content-Language: en-US
Content-Transfer-Encoding: quoted-printable

Hi Petter,

In the Configuration -> Configure page, do you have a Domain Name set?

I haven't been able to reproduce this issue, so I'm wondering what
conditions led to it.

Regards,
James


--6GrHH4Klan9ojdG73K5v9fOCV9A4sOR8f--

--9lM2xcNGB4K1rn9Xng8IFJDFwCIJpHL05
Content-Type: application/pgp-signature; name="signature.asc"
Content-Description: OpenPGP digital signature
Content-Disposition: attachment; filename="signature.asc"

-----BEGIN PGP SIGNATURE-----

iQJKBAEBCgA0FiEEfWrbdQ+RCFWJSEvmd8DHXntlCAgFAlnSvOMWHGp2YWxsZXJv
eUBtYWlsYm94Lm9yZwAKCRB3wMdee2UICDqjD/9qnDS3qT3DujljadARhgYpgsIj
PjlKDAd1hOEdEBJuGbRYQv8kYqHnMVk05rYZWBsUfcNx12ROgu3GnKv/xQsh+PBb
U6alQauwZWNWW94inqlK/uDZ7LNIDPIHvYTEcErSKUkuLpxE1+SXiuJY+NFdFDvo
bTsJG1D3zj+jhaac8xoPFtk6iOobUlYdvUvhPHbnddnDpGrM5CGl7DMYh9+iweW/
O+u6CwzCSm7GIloR7sYbWmPryGg0HI7Rn+GAaIzOnL8XDOaM/gmXoiMl4tipRMP6
q15/ecxJNbTW7oUbG298Y8TPvBvANelvwVgixE8iqaf8LGfvYo/UwH4cBKngU7mP
wBWdcsaoKNjL1M072RHZflh9hG2kjrYoWgVQtCLX2Zq9o1Pbg4utktL05AdbMKAx
Brd+puaOlwX2H0oo+RY2tfSvWzc3+hkmutU9/muGNnUIv129Q+L7a1vNKIygvIbP
CCW6lTXmFFgchdy9a1bewidcWU+VAi1b9+lU3y2IR+V0DgFc7oMQTCp8ZFtA+Lpx
+1MLoV7ICUnQKSQfgwycMLBdjO/99lv6SaIcqF6eKAgpj943rvrLihfZKNIA/4Xz
D1SdoOEAlbsCt6q0JEEAr/99MZoWN4xLjgsaRxrWebvGzlTdOUSgxM/yYfEvs2S9
JQlK4wACMTO+9+7Kng==
=+YqC
-----END PGP SIGNATURE-----

--9lM2xcNGB4K1rn9Xng8IFJDFwCIJpHL05--

**Comment by FedericoCeratto** [comment]
BTS_msg_id: <2flwp4cbynd.fsf@diskless.uio.no>
BTS author: Petter Reinholdtsen <pere@hungry.com>

[James Valleroy]
> Hi Petter,
>
> In the Configuration -> Configure page, do you have a Domain Name set?

Nope, it was blank.  I tried to set it and then visit
Configuration->Certificates (Let's Encrypt), but I still get the 500.

-- 
Happy hacking
Petter Reinholdtsen
