### ISSUE TITLE
Plinth displayed partially blank.

### ISSUE THREAD

**Issue by kalakrumanov** [freedombox/Plinth#894]
I'm using raspberry pi 1, with image freedombox-testing-nonfree_0.9_raspberry-armel.

After updating and upgrading, plinth only shows one part of the website, not showing options neither apps. 

![screen shot 2017-07-07 at 7 44 23 pm](https://user-images.githubusercontent.com/16352883/27969889-05f45e04-634d-11e7-9b53-4b86d0f401ec.png)

![screen shot 2017-07-07 at 7 44 16 pm](https://user-images.githubusercontent.com/16352883/27969891-06015924-634d-11e7-96ff-8de5c037fd56.png)

No error in logs, as far as I'm concerned. What is happening? I don't know what to do, or what to reinstall. I have tried restarting several times.

**Comment by JoKeyser** [comment]
Hi, that looks very odd indeed, thanks for opening an issue about it.
To get more information, could you post the (maybe redacted) logs from `/var/log/plinth/status.log`?

**Comment by kalakrumanov** [comment]
Sorry, but my brother just flashed the SD card and I am reinstalling everything now. If the problem appears again, I will post the log that you suggested ;)

**Comment by kalakrumanov** [comment]
Again. Everything was OK until I updated and upgraded the system using apt-get in the terminal.

Here is what `tail -100 /var/log/plinth/status.lo` shows:

> [2017-07-08 11:03:23,846] plinth.module_loader INFO     Importing plinth.modules.deluge
> [2017-07-08 11:03:23,910] plinth.module_loader INFO     Importing plinth.modules.minetest
> [2017-07-08 11:03:23,981] plinth.module_loader INFO     Importing plinth.modules.ttrss
> [2017-07-08 11:03:24,060] plinth.module_loader INFO     Importing plinth.modules.power
> [2017-07-08 11:03:24,186] plinth.module_loader INFO     Importing plinth.modules.first_boot
> [2017-07-08 11:03:31,157] plinth.module_loader INFO     Importing plinth.modules.system
> [2017-07-08 11:03:31,260] plinth.module_loader INFO     Importing plinth.modules.radicale
> [2017-07-08 11:03:31,322] plinth.module_loader INFO     Importing plinth.modules.repro
> [2017-07-08 11:03:31,387] plinth.module_loader INFO     Importing plinth.modules.quassel
> [2017-07-08 11:03:31,429] plinth.module_loader INFO     Importing plinth.modules.config
> [2017-07-08 11:03:31,507] plinth.module_loader INFO     Importing plinth.modules.tor
> [2017-07-08 11:03:31,731] plinth.module_loader INFO     Importing plinth.modules.openvpn
> [2017-07-08 11:03:31,888] plinth.module_loader INFO     Importing plinth.modules.upgrades
> [2017-07-08 11:03:32,079] plinth.module_loader INFO     Importing plinth.modules.avahi
> [2017-07-08 11:03:32,148] plinth.module_loader INFO     Importing plinth.modules.monkeysphere
> [2017-07-08 11:03:32,231] plinth.module_loader INFO     Importing plinth.modules.dynamicdns
> [2017-07-08 11:03:32,621] plinth.module_loader INFO     Importing plinth.modules.letsencrypt
> [2017-07-08 11:03:32,723] plinth.module_loader INFO     Importing plinth.modules.mumble
> [2017-07-08 11:03:32,809] plinth.module_loader INFO     Importing plinth.modules.xmpp
> [2017-07-08 11:03:32,880] plinth.module_loader INFO     Importing plinth.modules.firewall
> [2017-07-08 11:03:32,988] plinth.module_loader INFO     Importing plinth.modules.pagekite
> [2017-07-08 11:03:33,387] plinth.module_loader INFO     Importing plinth.modules.users
> [2017-07-08 11:03:33,961] plinth.module_loader INFO     Importing plinth.modules.roundcube
> [2017-07-08 11:03:34,041] plinth.module_loader INFO     Importing plinth.modules.datetime
> [2017-07-08 11:03:34,979] plinth.actions INFO     Executing command - ['sudo', '-n', '/usr/share/plinth/actions/tor', 'get-hs']
> [2017-07-08 11:04:02,924] plinth.actions INFO     Executing command - ['sudo', '-n', '/usr/share/plinth/actions/pagekite', 'is-disabled']
> [2017-07-08 11:04:22,508] plinth.actions INFO     Executing command - ['sudo', '-n', '/usr/share/plinth/actions/pagekite', 'get-kite']
> [2017-07-08 11:04:39,548] plinth.__main__ INFO     Setting up CherryPy server
> [08/Jul/2017:11:04:39] ENGINE Listening for SIGTERM.
> [08/Jul/2017:11:04:39] ENGINE Listening for SIGUSR1.
> [08/Jul/2017:11:04:39] ENGINE Listening for SIGHUP.
> [08/Jul/2017:11:04:39] ENGINE Bus STARTING
> [08/Jul/2017:11:04:39] ENGINE Started monitor thread '_TimeoutMonitor'.
> [08/Jul/2017:11:04:40] ENGINE Serving on http://127.0.0.1:8000
> [08/Jul/2017:11:04:40] ENGINE Bus STARTED
> [2017-07-08 11:06:47,286] py.warnings    WARNING  /usr/lib/python3/dist-packages/bootstrapform/templatetags/bootstrap.py:84: RemovedInDjango110Warning: render() must be called with a dict, not a Context.
>   return template.render(context)
> 
> [2017-07-08 11:06:59,433] plinth.actions INFO     Executing command - ['sudo', '-n', '/usr/share/plinth/actions/ldap', 'create-user', 'kalak']
> [2017-07-08 11:07:05,490] plinth.actions INFO     Executing command - ['sudo', '-n', '/usr/share/plinth/actions/ldap', 'add-user-to-group', 'kalak', 'admin']
> [2017-07-08 11:07:14,815] py.warnings    WARNING  /usr/lib/python3/dist-packages/django/shortcuts.py:45: RemovedInDjango110Warning: The context_instance argument of render_to_string is deprecated.
>   using=using)
> 
> [08/Jul/2017:13:00:47] ENGINE Caught signal SIGTERM.
> [08/Jul/2017:13:00:47] ENGINE Bus STOPPING
> [08/Jul/2017:13:00:47] ENGINE HTTP Server cherrypy._cpwsgi_server.CPWSGIServer(('127.0.0.1', 8000)) shut down
> [08/Jul/2017:13:00:47] ENGINE Stopped thread '_TimeoutMonitor'.
> [08/Jul/2017:13:00:47] ENGINE Bus STOPPED
> [08/Jul/2017:13:00:47] ENGINE Bus EXITING
> [08/Jul/2017:13:00:47] ENGINE Bus EXITED
> [08/Jul/2017:13:00:47] ENGINE Waiting for child threads to terminate...
> [2017-07-08 13:05:21,791] plinth.__main__ INFO     Configured Django with applications - ['bootstrapform', 'django.contrib.auth', 'django.contrib.contenttypes', 'django.contrib.messages', 'stronghold', 'plinth', 'plinth.modules.ikiwiki', 'plinth.modules.networks', 'plinth.modules.shaarli', 'plinth.modules.diagnostics', 'plinth.modules.privoxy', 'plinth.modules.transmission', 'plinth.modules.names', 'plinth.modules.help', 'plinth.modules.owncloud', 'plinth.modules.apps', 'plinth.modules.deluge', 'plinth.modules.minetest', 'plinth.modules.ttrss', 'plinth.modules.power', 'plinth.modules.first_boot', 'plinth.modules.system', 'plinth.modules.radicale', 'plinth.modules.repro', 'plinth.modules.quassel', 'plinth.modules.config', 'plinth.modules.tor', 'plinth.modules.openvpn', 'plinth.modules.upgrades', 'plinth.modules.avahi', 'plinth.modules.monkeysphere', 'plinth.modules.dynamicdns', 'plinth.modules.letsencrypt', 'plinth.modules.mumble', 'plinth.modules.xmpp', 'plinth.modules.firewall', 'plinth.modules.pagekite', 'plinth.modules.users', 'plinth.modules.roundcube', 'plinth.modules.datetime']
> [2017-07-08 13:05:21,840] plinth.__main__ INFO     Creating or adding new tables to data file
> [2017-07-08 13:05:28,194] plinth.__main__ INFO     Configuration loaded from file - /etc/plinth/plinth.config
> [2017-07-08 13:05:28,224] plinth.__main__ INFO     Script prefix - /plinth
> [2017-07-08 13:05:28,232] plinth.module_loader INFO     Importing plinth.modules.ikiwiki
> [2017-07-08 13:05:28,482] plinth.module_loader INFO     Importing plinth.modules.networks
> [2017-07-08 13:05:28,809] plinth.module_loader INFO     Importing plinth.modules.shaarli
> [2017-07-08 13:05:28,849] plinth.module_loader INFO     Importing plinth.modules.diagnostics
> [2017-07-08 13:05:28,909] plinth.module_loader INFO     Importing plinth.modules.privoxy
> [2017-07-08 13:05:28,952] plinth.module_loader INFO     Importing plinth.modules.transmission
> [2017-07-08 13:05:29,069] plinth.module_loader INFO     Importing plinth.modules.names
> [2017-07-08 13:05:29,131] plinth.module_loader INFO     Importing plinth.modules.help
> [2017-07-08 13:05:29,161] plinth.module_loader INFO     Importing plinth.modules.owncloud
> [2017-07-08 13:05:29,199] plinth.module_loader INFO     Importing plinth.modules.apps
> [2017-07-08 13:05:29,224] plinth.module_loader INFO     Importing plinth.modules.deluge
> [2017-07-08 13:05:29,259] plinth.module_loader INFO     Importing plinth.modules.minetest
> [2017-07-08 13:05:29,289] plinth.module_loader INFO     Importing plinth.modules.ttrss
> [2017-07-08 13:05:29,318] plinth.module_loader INFO     Importing plinth.modules.power
> [2017-07-08 13:05:29,370] plinth.module_loader INFO     Importing plinth.modules.first_boot
> [2017-07-08 13:05:33,996] plinth.module_loader INFO     Importing plinth.modules.system
> [2017-07-08 13:05:34,038] plinth.module_loader INFO     Importing plinth.modules.radicale
> [2017-07-08 13:05:34,064] plinth.module_loader INFO     Importing plinth.modules.repro
> [2017-07-08 13:05:34,099] plinth.module_loader INFO     Importing plinth.modules.quassel
> [2017-07-08 13:05:34,127] plinth.module_loader INFO     Importing plinth.modules.config
> [2017-07-08 13:05:34,157] plinth.module_loader INFO     Importing plinth.modules.tor
> [2017-07-08 13:05:34,242] plinth.module_loader INFO     Importing plinth.modules.openvpn
> [2017-07-08 13:05:34,335] plinth.module_loader INFO     Importing plinth.modules.upgrades
> [2017-07-08 13:05:34,412] plinth.module_loader INFO     Importing plinth.modules.avahi
> [2017-07-08 13:05:34,442] plinth.module_loader INFO     Importing plinth.modules.monkeysphere
> [2017-07-08 13:05:34,490] plinth.module_loader INFO     Importing plinth.modules.dynamicdns
> [2017-07-08 13:05:34,655] plinth.module_loader INFO     Importing plinth.modules.letsencrypt
> [2017-07-08 13:05:34,750] plinth.module_loader INFO     Importing plinth.modules.mumble
> [2017-07-08 13:05:34,779] plinth.module_loader INFO     Importing plinth.modules.xmpp
> [2017-07-08 13:05:34,812] plinth.module_loader INFO     Importing plinth.modules.firewall
> [2017-07-08 13:05:34,857] plinth.module_loader INFO     Importing plinth.modules.pagekite
> [2017-07-08 13:05:35,046] plinth.module_loader INFO     Importing plinth.modules.users
> [2017-07-08 13:05:35,375] plinth.module_loader INFO     Importing plinth.modules.roundcube
> [2017-07-08 13:05:35,416] plinth.module_loader INFO     Importing plinth.modules.datetime
> [2017-07-08 13:05:36,688] plinth.actions INFO     Executing command - ['sudo', '-n', '/usr/share/plinth/actions/pagekite', 'is-disabled']
> [2017-07-08 13:06:03,389] plinth.actions INFO     Executing command - ['sudo', '-n', '/usr/share/plinth/actions/pagekite', 'get-kite']
> [2017-07-08 13:06:30,797] plinth.actions INFO     Executing command - ['sudo', '-n', '/usr/share/plinth/actions/tor', 'get-hs']
> [2017-07-08 13:06:58,921] plinth.__main__ INFO     Setting up CherryPy server
> [08/Jul/2017:13:06:59] ENGINE Listening for SIGHUP.
> [08/Jul/2017:13:06:59] ENGINE Listening for SIGUSR1.
> [08/Jul/2017:13:06:59] ENGINE Listening for SIGTERM.
> [08/Jul/2017:13:06:59] ENGINE Bus STARTING
> [08/Jul/2017:13:07:00] ENGINE Started monitor thread '_TimeoutMonitor'.
> [08/Jul/2017:13:07:00] ENGINE Serving on http://127.0.0.1:8000
> [08/Jul/2017:13:07:00] ENGINE Bus STARTED
>

**Comment by JoKeyser** [comment]
Thanks for posting this, @kalakrumanov . The most suspicious line to me is:
```
py.warnings WARNING /usr/lib/python3/dist-packages/bootstrapform/templatetags/bootstrap.py:84: RemovedInDjango110Warning: render() must be called with a dict, not a Context.
return template.render(context)
```
However, I'm not sure whether this explains the missing content completely, since it's just a warning... To get more information, could you maybe also paste the apache2 error logs at `/var/log/apache2/error.log`?

**Comment by kalakrumanov** [comment]
I get this (I just refreshed the web, and it doesn't gets logged here, because the last thing here was 1 day ago)

> [Thu Jul 13 06:25:16.379803 2017] [mpm_prefork:notice] [pid 1102] AH00163: Apache/2.4.25 (Debian) mod_gnutls/0.7.5 GnuTLS/3.4.13 configured -- resuming normal operations
> [Thu Jul 13 06:25:16.380150 2017] [core:notice] [pid 1102] AH00094: Command line: '/usr/sbin/apache2'
> [Thu Jul 13 07:46:00.056148 2017] [authz_core:error] [pid 31118] [client 209.126.117.58:62079] AH01630: client denied by server configuration: proxy:http://127.0.0.1:8000/plinth
> [Thu Jul 13 08:21:21.212189 2017] [authz_core:error] [pid 32355] [client 119.1.109.20:1986] AH01630: client denied by server configuration: proxy:http://127.0.0.1:8000/plinth, referer: http://80.174.93.168:80
> [Thu Jul 13 09:19:25.813674 2017] [authz_core:error] [pid 31117] [client 185.153.197.214:61119] AH01630: client denied by server configuration: proxy:http://127.0.0.1:8000/plinth
> [Thu Jul 13 12:03:01.849570 2017] [authz_core:error] [pid 32355] [client 23.253.57.28:48408] AH01630: client denied by server configuration: proxy:http://127.0.0.1:8000/plinth
> [Thu Jul 13 12:37:32.345853 2017] [:error] [pid 31115] [client 113.107.183.45:57844] script '/var/www/html/wp-login.php' not found or unable to stat
> [Thu Jul 13 14:46:22.790057 2017] [authz_core:error] [pid 31119] [client 173.254.236.114:4109] AH01630: client denied by server configuration: proxy:http://127.0.0.1:8000/plinth
> [Thu Jul 13 15:06:14.086185 2017] [authz_core:error] [pid 32355] [client 103.26.77.45:61265] AH01630: client denied by server configuration: proxy:http://127.0.0.1:8000/plinth
> [Thu Jul 13 17:08:53.453314 2017] [authz_core:error] [pid 31115] [client 119.1.109.20:2470] AH01630: client denied by server configuration: proxy:http://127.0.0.1:8000/plinth, referer: http://80.174.93.168:80
> [Thu Jul 13 18:11:06.449937 2017] [:error] [pid 32355] [client 191.180.40.240:52551] script '/var/www/html/command.php' not found or unable to stat
> [Thu Jul 13 22:49:52.532532 2017] [gnutls:warn] [pid 31116] (103)Software caused connection abort: [client 192.168.1.45:59848] cleanup_gnutls_session: connection pool cleanup in progress but TLS session hasn't been terminated, trying to close

**Comment by JoKeyser** [comment]
Thanks for the logs. Hm, what strikes me as odd are the lines mentioning `[:error] [pid 31115] [client 113.107.183.45:57844] script '/var/www/html/wp-login.php' not found or unable to stat` and `[:error] [pid 32355] [client 191.180.40.240:52551] script '/var/www/html/command.php' not found or unable to stat`.
Could this be related to a broken apache2 configuration, maybe you installed wordpress (wp), and this created a conflict?

**Comment by kalakrumanov** [comment]
Nope. Those errors where just after updating and upgrading with "apt-get", nothing else installed.

**Comment by JoKeyser** [comment]
Okay, I misinterpreted that. I guess these errors are because bots are trying to probe your box for a wordpress login site (which is "normal", unfortunately).

Since the issue happens after the update, it may be related to a problem with bootstrap, like issue #900. What still puzzles me that we don't find an error, just a warning. But maybe that's why it's "just" left blank, not crashing the site entirely.

**Comment by JoKeyser** [comment]
If you're not annoyed by tiny bit of editing, you could try the following to confirm or disprove the bootstrap hypothesis:

As user root, edit the file ` /usr/lib/python3/dist-packages/bootstrapform/templatetags/bootstrap.py` in 3 places (but make a backup copy beforehand).
There are 3 occurrences of a line with `contect = Context(somestuff)` in it. Strip off the `Context()` around `somestuff`.
For example, line 64 *should* be:
```python
    context = {'field': element, 'classes': markup_classes, 'form': element.form}
```
With some luck, it should work now (and we would know for sure what the problem is). I'm not sure whether you have to restart before this takes effect; probably not.

**Comment by kalakrumanov** [comment]
I have done it all, and it still only shows the main content, not the menu on the left.  Sorry, but at least we have tried a solution that doesn't take us to the solution.

**Comment by JoKeyser** [comment]
Thanks a lot, @kalakrumanov , too bad that this doesn't solve it, but at least we now know this issue is different from issue #900.

**Comment by JosephKiranBabu** [comment]
@JoKeyser Doing a `systemctl restart plinth` in my case didn't load the edited code from dist-packages. It's still displaying the same 500 error in case of #900. 
Deleting all the .pyc files in the system didn't fix it either.
`# find / -name "*.pyc" -delete`

**Comment by JoKeyser** [comment]
@JosephKiranBabu thanks for checking, too. It's really odd it should not work for you; I've just recreated these steps in a fresh vagrant image, and it worked again. Could you try with a fresh image? (Also, let's take this over to #900, here it doesn't seem to apply anyways.)

**Comment by JosephKiranBabu** [comment]
I actually tried it on my home FreedomBox running the latest unstable plinth deb. 0.14.0+ds-1

**Comment by JoKeyser** [comment]
@JosephKiranBabu thanks for checking, glad that we agree now; I get confused like that all the time too :).
So I think it's best to consider this issue as unrelated to #900.

**Comment by JoKeyser** [comment]
@kalakrumanov I now got a RPi 1 myself and am trying now to reproduce this issue, but everything keeps working for me...
I've started with [freedombox-testing-nonfree_0.9_raspberry-armel.img](http://ftp.freedombox.org/pub/freedombox/0.9/), which comes with Plinth version 0.9.4. After the first login, the unattended-upgrades kept working aimlessly for hours, so I reverted to do an `apt update` and `apt-get dist-upgrade`. Plinth is now version 0.14.0 (you should be able to see that in help->about, last line). When I do `cat /etc/issue`, I get "Debian GNU/Linux buster/sid".
What are your versions?

**Comment by kalakrumanov** [comment]
Absolutely @JoKeyser. I reinstalled everything, did` apt update` and `apt-get dist-upgrade` and now everything is working great.

Thanks! :)

**Comment by JoKeyser** [comment]
Okay, glad to hear it's working for you know. I'm closing the issue for now, as the original issue isn't really reproducible right now. I'll keep in mind and follow up on the weird fruitless unattended upgrades issue, but that seems another thing to me. @kalakrumanov thanks again for all your information, please keep informing any issues you run into.

**Comment by kalakrumanov** [comment]
FIY: 

The problem only happens when you: 

```
apt-get update 
apt-get upgrade
```

But if you:

```
apt-get update 
apt-get dist-upgrade
```

Thank everything is working perfect ;)

**Comment by JoKeyser** [comment]
Oh, thank you, that would explain a lot of my previous confusion. I'll check into this, and re-open the issue.

**Comment by JoKeyser** [comment]
Hm, I still can't reproduce. To get the error, I did `apt-get update && apt-get upgrade` as you wrote. 
Maybe noteworthy, during the upgrade I was asked about (and kept the old versions) of `/etc/firewalld/firewalld.conf` and `/etc/ldapscripts/ldapscripts.conf`.
After a system restart, I end up with Plinth 0.14 again - is that expected? Can you access "plinth/help/about/" in the broken system, to check what the version is of the broken (partially blank) one? Or alternatively, run `apt-cache show plinth` to get its version?

**Comment by jvalleroy** [comment]
@kalakrumanov You may be interested to try the stable image for raspberry pi 1, which has been uploaded to http://ftp.freedombox.org/pub/freedombox/stable-2017.06/.

Otherwise, for now, I think we can consider this to be a transient issue due to mismatched package versions in testing.

**Comment by kalakrumanov** [comment]
I had been really busy with my work, sorry. 

Thanks for your answers @JoKeyser and @jvalleroy  ;)
